### ISSUE TITLE
给你的when一点建议

### ISSUE THREAD

**Issue by pyg2007** [NibaZShab/NibaZShab.github.io#2]
# 你可能不看github，所以我还在酷安发了一遍
兄得你怕不是要把我的why功能抄的一干二净哦，变量名改都不改就放上来？hexo用你自己的仓库？小游戏用apt还不先update？

**Comment by NibaZShab** [comment]
变量名已改
hexo已注明是使用本人的仓库
小游戏apt已转为pkg
